### ISSUE TITLE
AssertionError spacegraphcats.cdbg.index_reads on branch `prot_search`

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#447] opened 2021-11-12 15:50 UTC
I wanted to take contigs extracted by `prot_search` and turn them into reads. See full list of commands in #379 (https://github.com/spacegraphcats/spacegraphcats/pull/379#issuecomment-964283090).

The `index_reads` step gave me an assertion error.
```
python -Werror -m spacegraphcats.cdbg.index_reads ../outputs/spacegraphcats/CAMI_low_k31 ../outputs/spacegraphcats/CAMI_low/reads.bgz ../outputs/spacegraphcats/CAMI_low_k31/reads.bgz.index --expect-paired -k 31
```
```
We will REQUIRE that some of the reads are in pairs (-P/--expect-paired)
Paired reads will be indexed together (default).
removing existing db '../outputs/spacegraphcats/CAMI_low_k31/reads.bgz.index'
loaded 3169682205 k-mers in index (192.5s)
walking read file: '../outputs/spacegraphcats/CAMI_low/reads.bgz'
1.50e+10 bp in 99796358 reads
99796358 paired of 99796358 reads; 0 singletons
found reads for 203573627 cDBG IDs
46220.0s seconds total
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/sgc_prot_search/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tereiter/miniconda3/envs/sgc_prot_search/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/miniconda3/envs/sgc_prot_search/lib/python3.8/site-packages/spacegraphcats/cdbg/index_reads.py", line 195, in <module>
    sys.exit(main())
  File "/home/tereiter/miniconda3/envs/sgc_prot_search/lib/python3.8/site-packages/spacegraphcats/cdbg/index_reads.py", line 176, in main
    assert max(total_cdbg_ids) + 1 == len(total_cdbg_ids)
AssertionError
```

But the files exist...

```
ls -lah ../outputs/spacegraphcats/CAMI_low_k31/
-rw-r--r-- 1 tereiter tereiter 302G Nov 11 20:32 reads.bgz.index
```

```
ls -lah ../outputs/spacegraphcats/CAMI_low/
-rw-r--r-- 1 tereiter tereiter 9.9G Nov 10 17:33 reads.bgz
```

And extracting reads runs (running now, will update if it fails).
```
python -Werror -m spacegraphcats.search.extract_reads ../outputs/spacegraphcats/CAMI_low/reads.bgz ../outputs/spacegraphcats/CAMI_low_k31/reads.bgz.index PF01297.19.fa.nbhds.gz -o PF01297.19.fa.nbhds.reads.fa
```

Some relevant version info...I installed from branch `prot_search`
```
snakemake-minimal         6.4.0              pyhdfd78af_0    bioconda
sourmash                  4.2.2                hdfd78af_0    bioconda
sourmash-minimal          4.2.2            py38h497a2fe_1    conda-forge
spacegraphcats            2.1.dev22+g567ed21          pypi_0    pypi
```

**Comment by taylorreiter** [comment] 2021-11-15 18:24
The extract reads command runs, but I get this looking at compare results:
```
== This is sourmash version 4.2.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 3 signatures total.

0-ZnuA-PF01297-cami-low-reads         [1.    0.143 0.018]
1-PF01297.19.fa.nbhds.fa              [0.143 1.    0.027]
2-PF01297.19.fa.nbhds.reads.fa        [0.018 0.027 1.   ]
min similarity in matrix: 0.018
```

So i'm guessing this error was real and led to the reads not being completely indexed, even though output files were created (e.g., the reads should contain all the kmers that are in the nbhds...)

**Comment by taylorreiter** [comment] 2021-11-15 19:52
https://github.com/spacegraphcats/spacegraphcats/pull/379#issuecomment-969229662
with --containment:
```
0-ZnuA-PF01297-cami-low-reads         [1.    0.219 0.018]
1-PF01297.19.fa.nbhds.fa              [0.293 1.    0.027]
2-PF01297.19.fa.nbhds.reads.fa        [0.888 0.974 1.   ]
```

**Comment by ctb** [comment] 2021-11-16 14:54
I'm a little bit confused about how you got all the results in #379 ([these](https://github.com/spacegraphcats/spacegraphcats/pull/379#issuecomment-969449234), specifically) while still encountering this error. Do those results come from the signature files only, and you haven't been able to index and extract the reads? I would guess so...

So, ideally, we'd want to know if this `AssertionError` (which is almost certainly a bug of some kind!) is caused by #379 before merging #379. Right?

**Comment by taylorreiter** [comment] 2021-11-16 15:29
Right, so as stated in the original issue above, I got the assertion error, but all of the files existed, so I just ignored it and did some analyses. I was eager to know what the files contained :) but yes, understanding it would be ideal before merge

I wasn't sure where to start though, should I just increase ram and try my commands again?

**Comment by ctb** [comment] 2021-11-16 15:37
It seems unlikely that the problem is due to memory, but 🤷. I think I should dig in a bit. What's the top level directory for are all these files, please?

**Comment by taylorreiter** [comment] 2021-11-16 15:49
`/home/tereiter/github/2021-cami-sgc-prot/`
Catlas build and multifasta query are in the Snakefile: `Snakefile`
Other files are in `prot_search`, with the accompanying readme `prot_search/try_prot_search.sh`

**Comment by ctb** [comment] 2021-11-16 16:19
lazy question: did you build the cDBG from the same reads you're indexing?

**Comment by ctb** [comment] 2021-11-16 16:20
if you get a chance to re-run the indexing step with 3600ce1 (latest `prot_search` branch from #379) I'd be interested in the output!

**Comment by taylorreiter** [comment] 2021-11-16 16:33
> lazy question: did you build the cDBG from the same reads you're indexing?

Yes!
> if you get a chance to re-run the indexing step with 3600ce1 (latest prot_search branch from #379) I'd be interested in the output!

okey dokey will do now!

**Comment by taylorreiter** [comment] 2021-11-16 18:47
>l azy question: did you build the cDBG from the same reads you're indexing?

Sigh. just re-read my code. They are in fact NOT the same reads I was indexing. i indexed the un-trimmed reads on accident. double sigh.

**Comment by ctb** [comment] 2021-11-16 18:55
On Tue, Nov 16, 2021 at 10:47:14AM -0800, Taylor Reiter wrote:
> >l azy question: did you build the cDBG from the same reads you're indexing?
> 
> Sigh. just re-read my code. They are in fact NOT the same reads I was indexing. i indexed the un-trimmed reads on accident. double sigh. 

AH HAH! <whew> that explains a lot :)

**Comment by ctb** [comment] 2021-11-16 22:36
I'll close this - can re-open if error reoccurs.

**Closed as completed** 2021-11-16 22:36 UTC
